version: '3.1'
services:
    jenkins:
        build:
            context: ./jenkins_files
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "53400:8080"
            - "53000:50000"
    cloud_container:
        build:
            context: ./cloud_sv_container
        restart: unless-stopped        
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./cloud_sv_container/ssh_key_pub:/ssh_keys