- name: Players app deploy
  hosts: cloud
  tasks:
    - name: deploy container image based
      become: no
      community.docker.docker_container:
        name: players-app
        image: justideas/players-app:latest
        ports:
          - "5000:5000"
        